<?php
$collection = $this->getCollection();
//echo $this->getAdvertiseType();
?>








<div class="container">
    <h2>List <a href="<?php echo $block->getUrl('sharma/index/add');?>">Add Post</a></h2>   

    <div style="width: 100%; background-color: pink;">

  <div style="width: 20%;float: left;">
   
  <div class="row">
    <div class="col-sm-4"><a href="<?php echo $block->getUrl('sharma/index/index').'?post_type=all';?>">All</a></div>
    <div class="col-sm-4"><a href="<?php echo $block->getUrl('sharma/index/index').'?post_type=open';?>">Open</a></div>
    <div class="col-sm-4"><a href="<?php echo $block->getUrl('sharma/index/index').'?post_type=archive';?>">Archive</a></div>
    </div>
       
  </div>

  <div style="width: 80%;float: right;">

    <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Post Content</th>
        <th>Status</th>
        <th>Created Date</th>
        <th colspan="2">Action</th>
      </tr>
    </thead>
    <tbody>

      <?php foreach ($collection as $data) {  $ids = $data['id'];?>

      <tr>
        <td><?php echo $data['id'];?></td>
        <td><?php echo $data['name'];?></td>
        <td><?php echo $data['post_content'];?></td>
        <td>
        <?php 
        if ($data['status'] == 1) 
        {
          echo "Open";
        } 
        else 
        {
         echo "Archive";
        }
        ?>
        </td>

        <td><?php echo $data['created_at'];?></td>

        <td><a href="<?php echo $block->getUrl('sharma/index/edit').'?id='.$ids;?>">Edit</a></td>
        <td><a href="<?php echo $block->getUrl('sharma/index/deletedata').'?id='.$ids;?>">Delete</a></td>
      </tr>

      <?php } ?>

    </tbody>
  </table>
    
  </div>


  </div>

  
</div>