
<?php
$collection = $this->getCollection();  //var_dump($collection->getData());
?>
<h1 class="clagtech_tab"><?php echo $this->getHelloWorldTxt();?></h1>

<div style="width: 100%; background-color: pink;">


  <div style="width: 20%;float: left;">
 

     <div class="clag_tab">
      <ul>
        <li><a href="#">Step-1</a></li>

        <li><a href="#">Step-2</a></li>

        <li><a href="#">Step-3</a></li>

        <li><a href="#">Step-4</a></li>

        <li><a href="#">Step-5</a></li>
      </ul>
    </div>

  
  </div>

  <div style="width: 80%;float: right;">


  <div class="clag_tab">

  <h3>Seller Registration</h3>
  </div>

  
  </div>

</div>


 <style type="text/css">
  .clagtech_tab{
    background-color: #526552;
    color: #fff;
    padding: 6px;
    border-radius: 5px;
    margin-top: 14px;
    margin-bottom: 18px;
    font-size: 27px;
  }

  .clag_tab{
    background-color: #f6f6f6;
    margin-left: 11px;
    margin-right: 11px;
    padding: 16px;
  }

  .clag_tab ul{
    list-style-type:none;
  }

  #archive{
    background-color: rgba(224, 43, 39, 0.78);
    border-radius: 3px;
    padding-left: 21px;
    padding-right: 21px;
    color: #fff;
  }
  #pending{
    background-color: rgba(255, 85, 1, 0.78);
    border-radius: 3px;
    color: #fff;
  }
  #approved{
    background-color: #547054;
    border-radius: 3px;
    color: #fff;
  }
  .statuswidth{
    padding: 5px;
    padding-left: 13px;
    padding-right: 13px;
  } 

  #notmatch{
    background-color: rgba(224, 43, 39, 0.8);
    color: #fff;
    padding: 25px;
    font-weight: bold;
    text-align: center;
    font-size: 18px;
  }
  </style>