<div>

<a href="<?php echo $this->getBaseUrl()?>sales/order/history/">
	<?php echo __('All Orders');?>
</a>

<a href="<?php echo $this->getBaseUrl()?>customlogin/customer/currentorder/">
	<?php echo __('Current Orders');?>
</a>

<a href="<?php echo $this->getBaseUrl()?>customlogin/customer/integratedorder/">
	<?php echo __('Integrated Order');?>
</a>

<a href="<?php echo $this->getBaseUrl()?>customlogin/customer/cancelorder/">
<?php echo __('Cancel Order');?>
</a>

</div>